SELECT
C.Customer_id 
#,COUNT(C.PRODUCT_KEY)
#,COUNT(DISTINCT(P.PRODUCT_KEY))
FROM CUSTOMER C 
LEFT JOIN PRODUCT P ON P.PRODUCT_KEY=C.PRODUCT_KEY
GROUP BY C.CUSTOMER_ID
HAVING COUNT(DISTINCT(P.PRODUCT_KEY))=(SELECT COUNT(DISTINCT(PRODUCT_KEY)) FROM Product)
